<div id="index-panels" class="panels">
	<div class="panel panel-1 open" role="main">
	   <div class="container c-open">
	      <div class="push">
	         <div id="top-stories" class="top-stories group">
	            <div class="group__header"><h2 class="group__title">For You</h2></div>
	            <div class="group__body">
	               <div id="stories" class="units-list units-list--separators">
	                  Loading stories
	               </div>
	            </div>
	         </div>
	      </div>
	   </div>
	</div>
</div>

<style type="text/css">
.top-stories .group__header {
	display: block;
}
</style>

<script type="text/javascript">
(function () {
	var article = '<div class="unit unit--regular unit--has-media">'
                     + '<a href="{{link}}" class="unit__link-wrapper">'
                        + '<div class="unit__media">'
                        + '</div>'
                         + '<div class="unit__body">'
                           + '<div class="unit__header">'
                              + '<h3 class="unit__title"><span class="cta">{{heading}}</span> </h3>'
                               + '<div class="unit__meta">'
                                 + '<div class="date" data-seconds="1360772945" data-datetime="13 February 2013">{{date}}</div>'
                              + '</div>'
                           + '</div>'
                           + '<div class="unit__summary"><p class="summary">{{summary}}</p></div>'
                        + '</div>'
                     + '</a>'
                   + '</div>';
	if(typeof(Storage)!=="undefined") {
		var items = {};
		var content = '';
	    for (var key in localStorage){
	    	items[key] = localStorage.getItem(key);
	    }
	    jQuery.ajax({
            url: "/data/stories",
            type: 'POST',
            data: items,
            dataType: 'json',
        }).done(function(articles) {
        	for (var i = 0; i < articles.length; i++) {
        		content += article;
        		content = content.replace('{{heading}}', articles[i]['title']);
        		content = content.replace('{{summary}}', articles[i]['description']);
        		content = content.replace('{{link}}', articles[i]['url']);
        		var d = new Date(articles[i]['published']);
        		var month=new Array();
				month[0]="January";
				month[1]="February";
				month[2]="March";
				month[3]="April";
				month[4]="May";
				month[5]="June";
				month[6]="July";
				month[7]="August";
				month[8]="September";
				month[9]="October";
				month[10]="November";
				month[11]="December";
				var n = month[d.getMonth()];
        		var displayDate = d.getDate() + ' ' + n + ' ' + d.getFullYear();
        		content = content.replace('{{date}}', displayDate);
        	}
        	$('#stories').html(content);

        });
	} else if (window.localStorage.length === 0) {
		content = 'View some articles to store concepts.';
		$('#stories').html(content);
	} else {
		content = 'Local storage is not supported in your browser.';
		$('#stories').html(content);
	}
})();
</script>